version: 2

builds:
  - main: ./cmd/flow
    binary: flow
    ldflags:
      - -s -w -X github.com/milldr/flow/internal/cmd.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

universal_binaries:
  - replace: true

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

homebrew_casks:
  - name: flow
    repository:
      owner: milldr
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/milldr/flow
    description: Multi-repo workspace manager using git worktrees
    binaries:
      - flow
    hooks:
      post_install: |
        system_command "/usr/bin/xattr",
                       args: ["-dr", "com.apple.quarantine", "#{staged_path}"]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
